In [ ]:
# 정수형
import pandas as pd
s= pd.Series([95, 90, 85, 90, 95])
s

In [ ]:
# 실수형
s = pd.Series([4, 3.5, 3.8, 3, 3.7])
s

0    4.0
1    3.5
2    3.8
3    3.0
4    3.7
dtype: float64

In [ ]:
# 인덱스지정하기
s=pd.Series([90,80,95],index=['A','B','C'])
s

A    90
B    80
C    95
dtype: int64

In [ ]:
# 넘파이로 배열생성하기
import numpy as np
import pandas as pd
arr = np.arange(12).reshape(4,3)
print(arr)
print()
df = pd.DataFrame(arr)
print(df)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11


In [ ]:
# 딕셔너리로 배열생성하기
df = pd.DataFrame({'name':['장은실','오경선','양숙희'],
                    'score':[90,80,95],
                    'dept':['com','eng','math']})
df

name  score  dept
0  장은실     90   com
1  오경선     80   eng
2  양숙희     95  math

In [ ]:
#csv파일 불러오기
filename='/content/drive/MyDrive/mobile.csv'
df = pd.read_csv(filename)
df

Brand   Color  price
0  Samsung   Black    100
1       LG    Gold     70
2    Apple  Silver    150
3    Apple    Gray    120

In [ ]:
#filename='/content/drive/MyDrive/mobile.csv'
df = pd.read_csv(filename, index_col=0)
df

Color  price
Brand                 
Samsung   Black    100
LG         Gold     70
Apple    Silver    150
Apple      Gray    120

In [ ]:
filename='/content/drive/MyDrive/weather.csv'
df = pd.read_csv(filename)
df

date  temp  max_wind  mean_wind
0     2010-08-01  28.7       8.3        3.4
1     2010-08-02  25.2       8.7        3.8
2     2010-08-03  22.1       6.3        2.9
3     2010-08-04  25.3       6.6        4.2
4     2010-08-05  27.2       9.1        5.6
...          ...   ...       ...        ...
3648  2020-07-27  22.1       4.2        1.7
3649  2020-07-28  21.9       4.5        1.6
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

[3653 rows x 4 columns]

In [ ]:
df.shape

(3653, 4)

In [ ]:
df.head()

date  temp  max_wind  mean_wind
0  2010-08-01  28.7       8.3        3.4
1  2010-08-02  25.2       8.7        3.8
2  2010-08-03  22.1       6.3        2.9
3  2010-08-04  25.3       6.6        4.2
4  2010-08-05  27.2       9.1        5.6

In [ ]:
df.tail(3)

date  temp  max_wind  mean_wind
3650  2020-07-29  21.6       3.2        1.0
3651  2020-07-30  22.9       9.7        2.4
3652  2020-07-31  25.7       4.8        2.5

In [ ]:
df.index

RangeIndex(start=0, stop=3653, step=1)

In [ ]:
df.columns

Index(['date', 'temp', 'max_wind', 'mean_wind'], dtype='object')

In [ ]:
df.describe()

temp     max_wind    mean_wind
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000

In [ ]:
#기온(temp) 컬럼의 평균 출력하기
df['temp'].mean()

12.942102381604148

In [ ]:
df.sort_values(by='max_wind')

date  temp  max_wind  mean_wind
1514  2014-09-23  20.7       2.0        1.0
1134  2013-09-08  20.4       2.1        0.8
421   2011-09-26  18.7       2.1        0.3
1512  2014-09-21  20.4       2.2        1.2
1005  2013-05-02   7.1       2.2        0.8
...          ...   ...       ...        ...
2988  2018-10-06  19.4      26.0        7.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [ ]:
df.sort_values(by='max_wind', ascending=False)

date  temp  max_wind  mean_wind
2988  2018-10-06  19.4      26.0        7.0
3340  2019-09-23  15.0      25.8       11.0
1850  2015-08-25  20.1      25.3       14.9
3339  2019-09-22  15.7      23.1       11.9
1851  2015-08-26  17.4      22.6        8.1
...          ...   ...       ...        ...
1514  2014-09-23  20.7       2.0        1.0
559   2012-02-11  -0.7       NaN        NaN
560   2012-02-12   0.4       NaN        NaN
561   2012-02-13   4.0       NaN        NaN
3183  2019-04-19   7.8       NaN        2.3

[3653 rows x 4 columns]

In [ ]:
import pandas as pd
filename='/content/drive/MyDrive/bank.csv'
bank=pd.read_csv(filename)
bank['job'].value_counts()
bank['job'].value_counts(ascending=True)

student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: job, dtype: int64

In [ ]:
bank['job'].unique()

array(['management', 'technician', 'blue-collar', 'retired', 'services',
       'admin.', 'entrepreneur', 'self-employed', 'unemployed', 'student',
       nan, 'housemaid'], dtype=object)

In [ ]:
df['temp'] # df.temp
type(df['temp'])

pandas.core.series.Series

In [ ]:
df[['date','temp']]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df.loc[:,['date','temp']]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df.iloc[:,[0,1]]

date  temp
0     2010-08-01  28.7
1     2010-08-02  25.2
2     2010-08-03  22.1
3     2010-08-04  25.3
4     2010-08-05  27.2
...          ...   ...
3648  2020-07-27  22.1
3649  2020-07-28  21.9
3650  2020-07-29  21.6
3651  2020-07-30  22.9
3652  2020-07-31  25.7

[3653 rows x 2 columns]

In [ ]:
df[0:3]

date  temp  max_wind  mean_wind
date                                             
2010-08-01  2010-08-01  28.7       8.3        3.4
2010-08-02  2010-08-02  25.2       8.7        3.8
2010-08-03  2010-08-03  22.1       6.3        2.9

In [ ]:
df.index=df['date']
df.loc['2010-08-01',['temp','mean_wind']]

temp         28.7
mean_wind     3.4
Name: 2010-08-01, dtype: object

In [ ]:
df.iloc[3]

date         2010-08-04
temp               25.3
max_wind            6.6
mean_wind           4.2
Name: 2010-08-04, dtype: object

In [ ]:
df.iloc[1:3,0:2]

date  temp
date                        
2010-08-02  2010-08-02  25.2
2010-08-03  2010-08-03  22.1

In [ ]:
w=df['temp']>=30
df[w]

date  temp  max_wind  mean_wind
date                                             
2013-08-08  2013-08-08  31.3       7.8        4.6
2013-08-09  2013-08-09  30.6       9.9        6.4
2013-08-10  2013-08-10  30.6       7.4        3.8
2018-07-23  2018-07-23  30.5       6.5        1.6
2018-08-04  2018-08-04  30.3       5.8        3.0

In [ ]:
w=(df['temp']>=30) & (df['max_wind']>=9)
df[w]

date  temp  max_wind  mean_wind
date                                             
2013-08-09  2013-08-09  30.6       9.9        6.4

In [ ]:
w=df['temp']==df['temp'].max()
df[w]

date  temp  max_wind  mean_wind
date                                             
2013-08-08  2013-08-08  31.3       7.8        4.6

In [ ]:
df[df['max_wind'].isna()]

date  temp  max_wind  mean_wind
date                                             
2012-02-11  2012-02-11  -0.7       NaN        NaN
2012-02-12  2012-02-12   0.4       NaN        NaN
2012-02-13  2012-02-13   4.0       NaN        NaN
2019-04-19  2019-04-19   7.8       NaN        2.3

In [ ]:
# 결측데이터 컬럼별 확인
df.isnull().sum()

date         0
temp         0
max_wind     4
mean_wind    6
dtype: int64

In [ ]:
df2=df.dropna()
df2.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
# 결측 데이터 대체
df.fillna(df.mean(),inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [ ]:
df.isnull().sum()

date         0
temp         0
max_wind     0
mean_wind    0
dtype: int64

In [ ]:
filename='/content/drive/MyDrive/dust1.xlsx'
dust=pd.read_excel(filename)
dust.head()

지역     망   측정소코드 측정소명  ...    NO2  PM10  PM25                주소
0  서울 송파구  도시대기  111273  송파구  ...  0.066    50    18  서울 송파구 백제고분로 236
1  서울 송파구  도시대기  111273  송파구  ...  0.058    48    20  서울 송파구 백제고분로 236
2  서울 송파구  도시대기  111273  송파구  ...  0.055    44    20  서울 송파구 백제고분로 236
3  서울 송파구  도시대기  111273  송파구  ...  0.055    40    20  서울 송파구 백제고분로 236
4  서울 송파구  도시대기  111273  송파구  ...  0.053    38    17  서울 송파구 백제고분로 236

[5 rows x 12 columns]

In [ ]:
# 컬럼(변수) 삭제하기
dust=dust.drop(['지역','망','측정소코드'], axis=1)


In [ ]:
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236

In [ ]:
# 컬럼생성하기
dust['city']='서울'

In [ ]:
dust.head()

측정소명        측정일시    SO2   CO     O3    NO2  PM10  PM25                주소 city
0  송파구  2021040101  0.004  1.0  0.002  0.066    50    18  서울 송파구 백제고분로 236   서울
1  송파구  2021040102  0.004  0.8  0.002  0.058    48    20  서울 송파구 백제고분로 236   서울
2  송파구  2021040103  0.004  0.8  0.002  0.055    44    20  서울 송파구 백제고분로 236   서울
3  송파구  2021040104  0.003  0.8  0.002  0.055    40    20  서울 송파구 백제고분로 236   서울
4  송파구  2021040105  0.004  0.8  0.002  0.053    38    17  서울 송파구 백제고분로 236   서울

In [ ]:
dust.rename(columns={'측정소명':'name',
                     '측정일시':'date',
                     '주소':'addr'}, inplace=True)

In [ ]:
dust.columns

Index(['name', 'date', 'SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', 'addr',
       'city'],
      dtype='object')

In [ ]:
dust.dtypes

name     object
date      int64
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
# 숫자 int형을 문자열형으로 변환
dust['date']=dust['date'].astype(str)
dust['date']=dust['date'].str.slice(0,8)
dust.dtypes

name     object
date     object
SO2     float64
CO      float64
O3      float64
NO2     float64
PM10      int64
PM25      int64
addr     object
city     object
dtype: object

In [ ]:
dust['date']=pd.to_datetime(dust['date'])
dust.dtypes

name            object
date    datetime64[ns]
SO2            float64
CO             float64
O3             float64
NO2            float64
PM10             int64
PM25             int64
addr            object
city            object
dtype: object

In [ ]:
dust['year']=dust['date'].dt.year
dust['month']=dust['date'].dt.month
dust['day']=dust['date'].dt.day
dust.head()

name       date    SO2   CO     O3  ...              addr  city  year month day
0  송파구 2021-04-01  0.004  1.0  0.002  ...  서울 송파구 백제고분로 236    서울  2021     4   1
1  송파구 2021-04-01  0.004  0.8  0.002  ...  서울 송파구 백제고분로 236    서울  2021     4   1
2  송파구 2021-04-01  0.004  0.8  0.002  ...  서울 송파구 백제고분로 236    서울  2021     4   1
3  송파구 2021-04-01  0.003  0.8  0.002  ...  서울 송파구 백제고분로 236    서울  2021     4   1
4  송파구 2021-04-01  0.004  0.8  0.002  ...  서울 송파구 백제고분로 236    서울  2021     4   1

[5 rows x 13 columns]

In [ ]:
filename='/content/drive/MyDrive/nation.xlsx'
s1=pd.read_excel(filename)
s1

국적코드  성별    입국객수    증가수
0  A01  남성  125000   8000
1  A01  여성  130000  10000
2  A05  남성     300     10
3  A05  여성     200     50
4  A06  남성  158912  24486
5  A06  여성  325000  63466

In [ ]:
filename='/content/drive/MyDrive/code.xlsx'
s2=pd.read_excel(filename)
s2

국적코드  국적명
0  A01  필리핀
1  A02   일본
2  A03   미국
3  A04   중국
4  A05   호주
5  A06  베트남
6  A07  스위스
7  A99   기타

In [ ]:
pd.merge(s1,s2,on='국적코드')

국적코드  성별    입국객수    증가수  국적명
0  A01  남성  125000   8000  필리핀
1  A01  여성  130000  10000  필리핀
2  A05  남성     300     10   호주
3  A05  여성     200     50   호주
4  A06  남성  158912  24486  베트남
5  A06  여성  325000  63466  베트남