In [23]:
import random

size = 5
num_list = [[random.randint(0,255) for _ in range(size)] for _ in range(size)]

for i in range(size):
    for k in range(size):
        num_list = random.randint(0,255)

for i in range(size):
    for k in range(size):
        print("%2d" % num_list[i][k], end=' ')
    print()
print()

for i in range(size):
    for k in range(size):
        num_list[i][k] +=100

for i in range(size):
    for k in range(size):
        print('%3d' % num_list[i][k],end = ' ')
    print()






TypeError: 'int' object is not subscriptable

In [24]:
import numpy as np

size = 5
arr = np.random.randint(0,255, size=(size,size))

print(arr)
print()

arr += 100
print(arr)

[[169 116 110  65 117]
 [ 19 222 220  34 206]
 [184 141 180 244  66]
 [193 108 111  26 137]
 [111 233  96  52 113]]

[[269 216 210 165 217]
 [119 322 320 134 306]
 [284 241 280 344 166]
 [293 208 211 126 237]
 [211 333 196 152 213]]


In [30]:
import numpy

size = 3
arr = numpy.random.randint(0,255, size = (size,size))

print(arr)
sum = 0
arr *= 2
print(arr)
for i in range(size):
    for k in range(size):
        sum += arr[i][k]

print('평균값은', sum /(size*size))


[[ 24  71 206]
 [175  64  79]
 [ 25   9 182]]
[[ 48 142 412]
 [350 128 158]
 [ 50  18 364]]
평균값은 185.55555555555554


In [36]:
import numpy as np
import random

plist = [random.randint(0,255) for _ in range(5)]
print('파이썬 리스트 > ',plist)

arr1 = np.array(plist)
print('array(plist) >>',arr1)

arr2 = np.arange(5)
print('arange(5) >>',arr2)

arr3 = np.arange(3,8)
print('arage(3,8)>>',arr3)

arr4 = np.ones(5)
print('ones(5) >> ', arr4)

arr5 = np.ones((3,4))
print('ones((3,4)) >> ', arr5)

arr6 = np.zeros(5)
print('zeros(5)>>' ,arr6)

arr7 = np.empty(6)
print('empty(6)>>' ,arr7)

arr8 = np.full((5),33)
print('full(5,33) >>',arr8)

arr9 = np.identity(5)
print('identity(5) >>\n', arr9)



파이썬 리스트 >  [236, 98, 207, 143, 34]
array(plist) >> [236  98 207 143  34]
arange(5) >> [0 1 2 3 4]
arage(3,8)>> [3 4 5 6 7]
ones(5) >>  [1. 1. 1. 1. 1.]
ones((3,4)) >>  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
zeros(5)>> [0. 0. 0. 0. 0.]
empty(6)>> [6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307
 1.42413555e-306 1.78019082e-306]
full(5,33) >> [33 33 33 33 33]
identity(5) >>
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [78]:
import numpy as np
import random

pList1 = [10, 20, 30, 40]
pList2 = [10, 20, 30, 40.0]

numpyAry1 = np.array(pList1)
print(numpyAry1, numpyAry1.dtype)

numpyAry1 = np.array(pList2)
print(numpyAry1, numpyAry1.dtype)

numpyAry2 = np.array(pList1, dtype=np.float32)
print(numpyAry2, numpyAry2.dtype)

numpyAry3 = np.arange(5)
print(numpyAry3, numpyAry3.dtype)

numpyAry4 = np.ones(5)
print(numpyAry4, numpyAry4.dtype)

numpyAry5 = np.ones(5, dtype=np.uint8)
print(numpyAry5, numpyAry5.dtype)

numpyAry6 = numpyAry5.astype(np.float16)
print(numpyAry6, numpyAry6.dtype)

[10 20 30 40] int32
[10. 20. 30. 40.] float64
[10. 20. 30. 40.] float32
[0 1 2 3 4] int32
[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] uint8
[1. 1. 1. 1. 1.] float16


In [3]:
import numpy
arr = numpy.random.randint(0,255,size=(2,3))
print(arr.dtype)
print(arr.ndim)
arr.shape

int32
2


(2, 3)

In [5]:
arr = numpy.random.randint(0,255,size=(2,3))
arr = arr - 100

print(arr) 

arr = arr + arr  ### 브로드캐스팅

print(arr)

[[137  35 -19]
 [ 32 104 -85]]
[[ 274   70  -38]
 [  64  208 -170]]


In [6]:
#배열의 크기가 다른 연산
arr1 = numpy.array([[1,2],[3,4]])
arr2 = numpy.array([100,200])

arr1 + arr2

array([[101, 202],
       [103, 204]])

In [7]:
arr = numpy.random.randint(0,255,size=(2,3))
arr = 1/arr
print(arr)

[[0.00512821 0.0045045  0.01470588]
 [0.00961538 0.00515464 0.01388889]]


In [15]:
import random
SIZE = 5
list1 = []
value = 1
for _ in range(SIZE):
    tmplist = []
    for _ in range(SIZE):
        tmplist.append(value)
        value +=1
    list1.append(tmplist)

for i in range(SIZE):
    for k in range(SIZE):
        print('%3d'% list1[i][k],end=' ')
    print()
nsize = 3
startrow = 1
startcol = 1 
list2 = []
for i in range(startrow,startrow+nsize):
    tmplist = []
    for k in range(startcol,startcol+nsize):
        tmplist.append(list1[i][k])
    list2.append(tmplist)

for i in range(nsize):
    for k in range(nsize):
        print('%3d' % list2[i][k], end = ' ')
    print()


  1   2   3   4   5 
  6   7   8   9  10 
 11  12  13  14  15 
 16  17  18  19  20 
 21  22  23  24  25 
  7   8   9 
 12  13  14 
 17  18  19 


In [25]:
arr = numpy.arange(1,17)
arr = arr.reshape(4,4)
print(arr[1])
print(arr[1, 0:4])
print(arr[1, :4])

[5 6 7 8]
[5 6 7 8]
[5 6 7 8]


In [37]:
arr = numpy.arange(1,17)
arr = arr.reshape(4,4)
print(arr[2:])
print(arr[2:4,])
print(arr[2:4,:])

print(arr[:,1])
print(arr[0:4,1])
#print[arr[,1]]    ##행은 비워두면 안됨!!!!!!!!!!!!!!!!!!!!!
print(arr[:,2:])
print(arr[0:4,2:4])
print(arr[1:3,1:3])

print(arr[[1,3],:])
print(arr[:,[1,3]])

[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[ 2  6 10 14]
[ 2  6 10 14]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 6  7]
 [10 11]]
[[ 5  6  7  8]
 [13 14 15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [48]:
arr = numpy.arange(1,26)
arr = arr.reshape(5,5)

for i in range(5):
    for k in range(5):
        print(arr[i][k],end=' ')
    print()


print(arr[1:4,1:4])

1 2 3 4 5 
6 7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 
21 22 23 24 25 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [50]:
arr1 = numpy.zeros((2,2),dtype=numpy.int8)
arr2 = numpy.ones((2,2),dtype=numpy.int8)

print(numpy.concatenate((arr1,arr2),axis=0))
print(numpy.concatenate((arr1,arr2),axis=1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]]
[[0 0 1 1]
 [0 0 1 1]]


In [76]:
import random
ran_num = [8,12,16,20]
ran = random.choice(ran_num)

arr = numpy.arange(1,ran*ran + 1)
arr = arr.reshape(ran,ran)

for x in arr:
    for i in x:
        print('%2d'%i , end=' ')
    print()
print()
for i in range (int(ran/2),ran):
    for k in range(int(ran/2),ran):
        print('%2d'%arr[i][k],end=' ')
    print()

 1  2  3  4  5  6  7  8 
 9 10 11 12 13 14 15 16 
17 18 19 20 21 22 23 24 
25 26 27 28 29 30 31 32 
33 34 35 36 37 38 39 40 
41 42 43 44 45 46 47 48 
49 50 51 52 53 54 55 56 
57 58 59 60 61 62 63 64 

37 38 39 40 
45 46 47 48 
53 54 55 56 
61 62 63 64 


In [80]:
arr1 = np.random.randint(0,255,size=(3,3))
arr2 = np.random.randint(0,255,size=(3,3))

print(arr1)
print(arr2)
print(np.maximum(arr1,arr2)) # 두배열을 비교해서 큰값을 출력
print(np.greater(arr1,arr2)) # 두배열을 비교해서 arr1 > arr2 이면 True 아니라면 False를 출력하는 넘파이 함수

[[252  43 134]
 [ 11 217   5]
 [ 15  64 238]]
[[231  77  47]
 [237 164 149]
 [130 235 227]]
[[252  77 134]
 [237 217 149]
 [130 235 238]]
[[ True False  True]
 [False  True False]
 [False False  True]]


In [84]:
arr = numpy.arange(1,11) ##배열의 속성을 알아보는 것

print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

int32
1
(10,)
10


In [89]:
arr = numpy.arange(10,51) ## 배열 거꾸로 출력하기
# k = -1
# for i in range(41):
#     print(arr[k])
#     k -= 1
print (arr[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [93]:
arr1 = np.random.randint(0,255,size=(10,10)) ##배열안에 최대값 최소값 찾기
print(numpy.max(arr1))
print(numpy.min(arr1))

250
0


In [97]:
arr1 = numpy.arange(0,9)
arr1 = arr1.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [100]:
arr = np.arange(1,25).reshape(4,6)
print(arr)
print(arr[2:,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [104]:
print(arr[(arr>=10)&(arr<=20)])


[10 11 12 13 14 15 16 17 18 19 20]


In [109]:
arr = np.arange(1,21)

print(f'마지막 원소:{arr[-1]}')
print(f'모든 원소의 합:{numpy.sum(arr)}')
print(f'모든원소의 평균:{numpy.sum(arr)/len(arr)}')
print(arr.reshape(4,5))

마지막 원소:20
모든 원소의 합:210
모든원소의 평균:10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [120]:
list1 = [200,150,180,220,250]

arr = numpy.array(list1)
new = arr * 1.5
print(f'인상된 금액: {arr * 1.5}')
print(f'평균금액: {numpy.sum(arr * 1.5)/len(arr)}')
print(f'평균이상의 원소 : {new[new >=numpy.sum(arr * 1.5)/len(arr)]}')
print(f'평균이상인 원소의 개수 :{len(new[new >=numpy.sum(arr * 1.5)/len(arr)])} ')

인상된 금액: [300. 225. 270. 330. 375.]
평균금액: 300.0
평균이상의 원소 : [300. 330. 375.]
평균이상인 원소의 개수 :3 
