In [2]:
import numpy as np

arr1 = np.random.randint(0,255,size=(3,3))
print(arr1)
arr2 = np.random.randint(0,255,size=(3,3))
print(arr2)
carr = np.random.choice([True,False],size=(3,3))
print(carr)
np.where(carr,arr1,arr2)    ### carr가 True면 arr1을 출력, False라면 arr2를 출력

[[126  57 146]
 [133  55 200]
 [199  82  26]]
[[ 63  10  53]
 [ 13  35 160]
 [248  87  45]]
[[ True False  True]
 [False False False]
 [False  True False]]


array([[126,  10, 146],
       [ 13,  35, 160],
       [248,  82,  45]])

In [3]:
arr = np.random.randint(-128, 127, size=(3,3))
print (arr)
print(np.where(arr < 0, 0, arr)) #where(조건,True값,False값)

[[ -12  -33 -115]
 [  43  -17  121]
 [ -18  114  103]]
[[  0   0   0]
 [ 43   0 121]
 [  0 114 103]]


In [4]:
arr = np.random.randint(0,255,size=10)

print(arr)
print(arr.sum()) #총 합
print(arr.mean()) # 평균

[  4 214 212 124 249 196 105 121  62 179]
1466
146.6


In [6]:
arr = np.random.randint(0,255,size=(3,3))

print(arr)
print(arr.sum())
print(arr.sum(axis=0))  ### 열끼리 더함  세로의 합
print(arr.sum(axis=1))  ### 행끼리 더함  가로의 합

[[ 47 180  12]
 [ 15 114 128]
 [192 216  47]]
951
[254 510 187]
[239 257 455]


In [10]:
arr = np.random.randint(0,255,size=(3,3))
print(arr)
print((arr>128).sum()) # 조건이 True인 개수를 셈
print(arr.min())
print(arr.max())

[[ 63  89   9]
 [159  11 246]
 [ 96  98 235]]
3
9
246
[[  9  63  89]
 [ 11 159 246]
 [ 96  98 235]]
[[ 96  98 235]
 [ 11 159 246]
 [  9  63  89]]


In [12]:
arr = np.random.randint(0,255,size=10)
print(arr)
print(np.sort(arr))
print(np.sort(arr)[::-1])

[180 244 190  33  65  23 160 240 213 194]
[ 23  33  65 160 180 190 194 213 240 244]
[244 240 213 194 190 180 160  65  33  23]


In [13]:
arr = np.random.randint(0,9,size = 10)
print (arr)
print(np.unique(arr)) #<< 리스트에서 중복된 값을 제거해줌

[0 8 3 5 5 6 6 7 6 0]
[0 3 5 6 7 8]


In [15]:
arr1 = np.random.randint(0,9,size=10)
arr2 = np.random.randint(0,9,size=10)
print(arr1)
print(arr2)
print(np.intersect1d(arr1,arr2))  ### 두 배열의 교집합구하기

[1 3 3 0 2 7 1 6 5 1]
[8 8 5 1 7 1 7 0 0 0]
[0 1 5 7]


In [16]:
import random
import time

SIZE = 10000

plist = [[random.randint(0,255)for _ in range(SIZE)]for _ in range(SIZE)]
nparr = np.random.randint(0,255,size=(SIZE,SIZE))

start = time.time()
for i in range(SIZE):
    for k in range(SIZE):
        plist[i][k] = 255 - plist[i][k]
end = time.time()
print('##리스트 처리시간: %10.2f초' % (end - start))


start = time.time()
nparr = 255 - nparr
end = time.time()
print('##넘파이 처리시간 : %10.2f 초' % (end-start))

##리스트 처리시간:      16.27초
##넘파이 처리시간 :       0.17 초
